name: Flex
markdown: kramdown
highlighter: pygments
exclude: ["LICENSE.txt", "README.md"]

baseurl: ""
permalink: /:title/

# default_locale_in_subfolder: true

# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"


# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["en", "es", "it", "ru"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
